import { Injector, OnDestroy, OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormControl, UntypedFormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { AlertService } from '../../../@core/services/alert.service';
import { AuthService } from '../../../@core/services/auth.service';
import { CommonDropdownsService } from '../../../@core/services/common-dropdowns.service';
import { DataStoreService } from '../../../@core/services/data-store.service';
import { LocalService } from '../../../@core/services/local.service';
import { PageBuilderAddService } from '../../../@core/services/page-builder-add.service';
import { PageBuilderService } from '../../page-builder-version/@core/page-builder.service';
import * as i0 from "@angular/core";
export declare class TabConfigComponent implements OnInit, OnDestroy {
    private _formBuilder;
    private _alert;
    private _route;
    private _router;
    private _storeservice;
    tabsForm: UntypedFormGroup;
    formData: any;
    id: string;
    pageTypeList: any;
    dropdownService: CommonDropdownsService;
    pageList: any;
    filteredPageList: any;
    pageBuilderAddService: PageBuilderAddService;
    pageBuilderService: PageBuilderService;
    authService: AuthService;
    orgSubs: Subscription;
    orgId: any;
    fieldList: any;
    allFieldList: any;
    parentFieldList: any;
    tempList: any;
    pageErrorShow: boolean;
    tabErrorShow: boolean;
    basicPageInformation: any;
    localStore: LocalService;
    httpService: any;
    RBACORG: any;
    constructor(injector: Injector, _formBuilder: UntypedFormBuilder, _alert: AlertService, _route: ActivatedRoute, _router: Router, _storeservice: DataStoreService);
    ngOnInit(): void;
    validationPage(): any;
    ngOnDestroy(): void;
    setCurrentFormData(): void;
    initTabConfigForm(): void;
    getPageTypes(): void;
    getAllPages(): void;
    private addTabGroup;
    get tabs(): UntypedFormControl[];
    addTab(): void;
    removeTab(_index: number): void;
    cancel(): void;
    saveTabs(publish: boolean): void;
    onChange(value: any, index: number): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<TabConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TabConfigComponent, "app-tab-config", never, {}, {}, never, never, false, never>;
}
