import { Location } from '@angular/common';
import { ElementRef, EventEmitter, Injector, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormioComponent } from '@formio/angular';
import { FileError, NgxfUploaderService } from 'ngxf-uploader';
import { SpeechRecognitionService } from '../../@core/service/speech-recognition.service';
import { OCRService } from '../../@core/service/ocr.service';
import { LocalService } from '../../@core/service/local.service';
import { DataStoreService } from '../../@core/service/data-store.service';
import { DynamicTabPageService } from '../../@core/service/dynamic-tab-page-service';
import { DynamicsearchService } from '../../@core/service/dynamicsearch.service';
import { AuthService } from '../../@core/service/auth.service';
import { AlertService } from '../../@core/service/alert.service';
import { AttachmentsService } from '../../@core/service/attachments.service';
import { OcrValidationService } from '../../@core/service/ocr-validation.service';
import { FormioService } from '../../@core/service/formio.service';
import { AppService } from '../../@core/service/app.service';
import * as i0 from "@angular/core";
export declare class DynamicPageComponent implements OnInit, OnDestroy {
    router: Router;
    private route;
    private _formIO;
    private readonly appService;
    private _storeservice;
    submitSuccess: EventEmitter<any>;
    submitFailed: EventEmitter<any>;
    formId: any;
    tabId: any;
    jsonForm: any;
    fromTitle: any;
    editId: any;
    id: any;
    submittedData: any;
    afterEntityName: string;
    afterRuleAppName: string;
    beforeEntityName: string;
    beforeRuleAppName: string;
    beforerulemethod: string;
    afterrulemethod: string;
    user: any;
    multiSelectDropDowns: Array<string>;
    pageId: any;
    sourceid: string;
    externalParameters: string;
    pageDataSubscription: any;
    isDialogPopup: boolean;
    private dialogRef;
    external_scanner: ElementRef;
    isReadOnly: boolean;
    showBack: boolean;
    isTitle: any;
    afterSubmit: EventEmitter<any>;
    personId: any;
    triggerRefresh: any;
    fromWorkFlow: boolean;
    clickedServiceCase: boolean;
    serviceId: any;
    speechRecogninitionOn: boolean;
    speechData: string;
    notification: string;
    organizationId: any;
    FormInputs: any[];
    scannerConfig: any;
    tabData: any;
    narrative: any;
    purpose: any;
    pagetype: string;
    localstorage: LocalService;
    sessionStorage: LocalService;
    location: Location;
    dataStore: DataStoreService;
    speechRecognitionService: SpeechRecognitionService;
    uploadService: NgxfUploaderService;
    ocr: OCRService;
    appointmentList: Promise<boolean> | undefined;
    isformIO: boolean;
    formIO: FormioComponent;
    currentYouthId: any;
    dynamicTabPageService: DynamicTabPageService;
    dynamicSearchService: DynamicsearchService;
    authService: AuthService;
    attachmentInfo: any;
    uploadedFiles: any;
    parentGridPage: string;
    parentGridPageId: any;
    alertService: AlertService;
    uploadedFile: any;
    isOcrForm: boolean;
    documentType: string;
    imgUrl: string;
    showOcrForm: boolean;
    attachmentService: AttachmentsService;
    imageData: {
        contentType: any;
        fileName: string;
    };
    tableschemaconfig: any;
    formResponse: any;
    action: string;
    contentArray: any[];
    templateResult: any;
    ocrValidationService: OcrValidationService;
    dataSub: any;
    btnVerify: boolean;
    editValue: any;
    loggedUser: any;
    providerData: any;
    check: any;
    showTabBack: boolean;
    httpService: any;
    constructor(injector: Injector, router: Router, route: ActivatedRoute, _formIO: FormioService, data: any, appService: AppService, _storeservice: DataStoreService);
    conditionCheckData(data: any): void;
    ngOnInit(): void;
    routerPageData(data: any): void;
    getPageTabs(): void;
    getRouterConfig(): void;
    getSource(): void;
    private getTemplate;
    conditionCheckTemplate(result: any): void;
    getConfiguration(): Promise<any>;
    loadIncidentData(): void;
    private callGetAPI;
    conditionCheckCallGetAPI(): void;
    formresponse(action: any): void;
    resultNullCheck(data: any): any;
    getActionSelect(result: any, action: any): void;
    getMultipleFrom(result: any): void;
    private processMultiSelectDropdowns;
    nextSubmit(event: any): void;
    onSubmit(submission: any): void;
    submiteWithoutId(requestData: any): void;
    addAttachment(info: any): void;
    submittedDate(result: any): void;
    submitToSurvey(): void;
    updateForm(requestData: any): void;
    closePopup(): void;
    goBack(): void;
    openBottomSheet(): void;
    modifyVideoContent(): void;
    customClickEvents(_data: any, event: any): void;
    redirect(): void;
    customEventsButton(event: any): void;
    downloadReport(data: any): void;
    downloadFile(s3BucketUrlName: any): void;
    customEvents(evt: any): void;
    speechToTextContent(): void;
    activateSpeechToText(ctrl: any, evt: any, item: any): void;
    conditionCheckError(narrativeElement: any, ctrl: any, evt: any, item: any, err: any): void;
    errorExecution(narrativeElement: any, ctrl: any, evt: any, item: any, err: any): void;
    micNotAvailableAlert(): string;
    micUnauthorisedAlert(): string;
    noSpeechAlert(): string;
    deActivateSpeechRecognition(ctrl: any): void;
    ngOnDestroy(): void;
    uploadFile(file: File | FileError | any): void;
    processResponseData(file: any): void;
    processOCRResponse(result: any): void;
    prepareFormKeyLabel(json: any): void;
    financeCustomEventsFunctionality(event: any): void;
    routeToGrid(val: any): void;
    customEvent(event: any): void;
    ocrUpload(files: any): void;
    condionCheckErrorAlert(error: any): void;
    getUpload(obj: any): void;
    verifiData(ocrDocumentDetails: any): void;
    conditionCheckVerify(element: any, ocrDocumentDetails: any, respose: any, jsonForm: any): void;
    getEmittedData(data: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DynamicPageComponent, [null, null, null, null, { optional: true; }, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DynamicPageComponent, "app-dynamic-page", never, { "editId": { "alias": "editId"; "required": false; }; "pageId": { "alias": "pageId"; "required": false; }; "sourceid": { "alias": "sourceid"; "required": false; }; "externalParameters": { "alias": "externalParameters"; "required": false; }; "isReadOnly": { "alias": "isReadOnly"; "required": false; }; }, { "afterSubmit": "afterSubmit"; }, never, never, false, never>;
}
