import { Injector, OnDestroy, OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AlertService } from '../../@core/services/alert.service';
import { AuthService } from '../../@core/services/auth.service';
import { DynamicsearchService } from '../../@core/services/dynamicsearch.service';
import { LocalService } from '../../@core/services/local.service';
import { PageBuilderAddService } from '../../@core/services/page-builder-add.service';
import { PageBuilderService } from './@core/page-builder.service';
import * as i0 from "@angular/core";
export declare class PageBuilderVersionComponent implements OnInit, OnDestroy {
    private router;
    private route;
    auth: AuthService;
    private localstore;
    pageList: any;
    tableColumns: any[];
    updateGrid: any;
    totalcount: number;
    id: number | string;
    pageBuilderService: PageBuilderService;
    pageBuilderAddService: PageBuilderAddService;
    dynamicSearchService: DynamicsearchService;
    gridId: string;
    gridOptions: {
        value: string;
        label: string;
        code: string;
    }[];
    filterOptions: any[];
    filterForm: UntypedFormGroup;
    fb: UntypedFormBuilder;
    alertService: AlertService;
    constructor(injector: Injector, router: Router, route: ActivatedRoute, auth: AuthService, localstore: LocalService);
    ngOnInit(): void;
    getVersionList(): void;
    activateVersion(event: any): void;
    goToPrevious(): void;
    setGridColumns(): void;
    viewVersions(evt: any): void;
    editTableRow(evt: any): void;
    viewTableRow(evt: any): void;
    duplicatePageVersion(evt: any): void;
    loadFilterForm(): void;
    getGridConfig(): void;
    setFilterOptions(colConfig: any): void;
    changeFilterOptions(e: any): void;
    checkconditionFilterOptions(isExists: any, value: any, code: any): void;
    conditionCheckElse(value: any, code: any): void;
    saveGridConfig(data: any): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PageBuilderVersionComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PageBuilderVersionComponent, "app-page-builder-version", never, {}, {}, never, never, false, never>;
}
