import { Router } from '@angular/router';
import { MenuItem } from 'primeng/api';
import { BehaviorSubject } from 'rxjs';
import { LocalService } from './local.service';
import { DataStoreService } from './data-store.service';
import * as i0 from "@angular/core";
export declare class PageBuilderAddService {
    private router;
    private localstore;
    private _storeservice;
    authorisedTabs: MenuItem[];
    httpService: any;
    constructor(router: Router, localstore: LocalService, _storeservice: DataStoreService);
    getFormData: BehaviorSubject<any>;
    currentFormData: import("rxjs").Observable<any>;
    setFormData(data: any): void;
    getBasicData: BehaviorSubject<any>;
    currentBasicData: import("rxjs").Observable<any>;
    setBasicData(data: any): void;
    getPageType: BehaviorSubject<any>;
    currentPageType: import("rxjs").Observable<any>;
    setPageType(data: string): void;
    getBasicDetailsbyId(id: any): any;
    pageAlertChecking(pagename: any, orgid: any, _body?: any): any;
    createPage(data: any): any;
    createAssetByVersion(pageid: any, versionid: any, assetData: any): any;
    getMenuList(data: any, id: any): any;
    getTableFields(param1: any, param2: any): any;
    createReportTable(data: any): any;
    getAllPage(url: any): any;
    getSchema(): any;
    getAllOrganisations(): any;
    editPageStatus(data: any, id: any): any;
    getOrgList(orgid: any): any;
    getUploadKey(data: any): any;
    getFormResponseAttachment(formid: any, responseid: any): any;
    deleteFormResponseAttachment(fileid: any): any;
    downloadFormResponseAttachment(data: any): any;
    returnToList(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PageBuilderAddService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<PageBuilderAddService>;
}
