import { Location } from '@angular/common';
import { Injector, OnDestroy, OnInit } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { MenuItem } from 'primeng/api';
import { Subscription } from 'rxjs';
import { PermissionStore } from '../../@core/permissions/permission.store';
import { AlertService } from '../../@core/services/alert.service';
import { AuthService } from '../../@core/services/auth.service';
import { CommonDropdownsService } from '../../@core/services/common-dropdowns.service';
import { LocalService } from '../../@core/services/local.service';
import { PageBuilderAddService } from '../../@core/services/page-builder-add.service';
import * as i0 from "@angular/core";
export declare class PageBuilderAddComponent implements OnInit, OnDestroy {
    private formBuilder;
    private router;
    private route;
    private alert;
    private permissionStore;
    formData: any;
    formDetails: UntypedFormGroup;
    pageTypeList: any;
    schemaList: any;
    templateJSON: any;
    layout: any;
    subscribeFormData: any;
    jsonForm: any;
    isShowDesign: boolean;
    rev: any;
    selectedPageValue: string;
    orgList: any;
    updateMessage: string | null;
    onlineUsersList: {
        shortNameUser: Array<any>;
        fullNameUser: Array<any>;
    };
    logedInUser: any;
    activeIndex: number;
    pageBuildertabs: MenuItem[];
    authorisedTabs: MenuItem[];
    labelText: string;
    checked2: boolean;
    auth: AuthService;
    localstorage: LocalService;
    location: Location;
    service: PageBuilderAddService;
    dropdownService: CommonDropdownsService;
    canChangeFormData: boolean;
    constructor(injector: Injector, formBuilder: UntypedFormBuilder, router: Router, route: ActivatedRoute, alert: AlertService, permissionStore: PermissionStore);
    id: string | null;
    onlineUserListSubscription: Subscription;
    updateNotificationSubscription: Subscription;
    ngOnInit(): void;
    onActiveIndexChange(event: number): void;
    fieldValidation(): boolean;
    getBasicInfo(): void;
    getPageUrl(): void;
    getPageAPi(url: any): void;
    setTimetoGetPage(): void;
    getAuthorisedTabs(page?: any): void;
    ngOnDestroy(): void;
    loadForm(): void;
    loadSchemas(): void;
    saveLayout(): void;
    resetForm: any;
    goToDesignPage(): void;
    formSubmit: any;
    setTooltip(displayValue: any): void;
    goBack(): void;
    getOrgList(): void;
    subscribeToPageDesign(componentRef: any): void;
    unsubscribeToPageDesign(): void;
    showUpdateNotification(event: any, _this: any): void;
    closeUpdateNotification(): void;
    onlineUserList(event: any, _this: any): void;
    getChange(text: any): void;
    updatePageStatus(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PageBuilderAddComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PageBuilderAddComponent, "app-page-builder-add", never, {}, {}, never, never, false, never>;
}
