import { HttpService } from './http.service';
import { BehaviorSubject } from 'rxjs';
import * as i0 from "@angular/core";
export declare class DynamicsearchService {
    private _httpService;
    port: string;
    port_communication: string;
    port_document: string;
    port_searchinput: string;
    port_report: string;
    onChangePageEventData: any;
    onChangePageEventId: any;
    onChangePageUserData: any;
    onChangePersonId: any;
    onChangeConfigData: any;
    inputFieldId: any;
    personTabName: any;
    personHealthTabName: any;
    personFinanceTabName: any;
    clickedId: any;
    rowData: any;
    caseNumberAfterApproval: any;
    private isPageDesign;
    observePage: import("rxjs").Observable<boolean>;
    data: BehaviorSubject<any>;
    sourceId: BehaviorSubject<any>;
    sourceIdService: BehaviorSubject<any>;
    id: BehaviorSubject<any>;
    pageId: BehaviorSubject<any>;
    moduleid: BehaviorSubject<any>;
    purposeid: BehaviorSubject<any>;
    workFlowDesign: BehaviorSubject<any>;
    workFlowStatus: BehaviorSubject<any>;
    result: BehaviorSubject<any>;
    constructor(_httpService: HttpService);
    set clickableData(data: any);
    get clickableData(): any;
    set personTabNameData(data: any);
    get personTabNameData(): any;
    set personHealthTabNameData(data: any);
    get personHealthTabNameData(): any;
    set personFinanceTabNameData(data: any);
    get personFinanceTabNameData(): any;
    set clickedIdData(data: any);
    get clickedIdData(): any;
    set caseNumberAfterApprovalData(data: any);
    get caseNumberAfterApprovalData(): any;
    set clickedRowData(data: any);
    get clickedRowData(): any;
    getGridUserPreference(id: any): import("rxjs").Observable<Object>;
    getStaticGridConfig(id: any): import("rxjs").Observable<Object>;
    saveGridUserPreference(data: any): import("rxjs").Observable<Object>;
    sendMail(data: any): import("rxjs").Observable<Object>;
    generateDocument(data: any, typeCheck: any): import("rxjs").Observable<Object>;
    exportData(data: any, link: any): import("rxjs").Observable<Object>;
    saveSearchCriteria(data: any): import("rxjs").Observable<Object>;
    startScheduling(data: any, url: any): import("rxjs").Observable<Object>;
    startSchedulingNoUrl(data: any, id: any): import("rxjs").Observable<Object>;
    getTemplate(formId: any): import("rxjs").Observable<Object>;
    getTemplateView(formId: any): import("rxjs").Observable<Object>;
    getPageTabs(pageId: any): import("rxjs").Observable<Object>;
    changePage(page: any): void;
    getFormResponse(pageId: string): Promise<Object>;
    getProviderData(providerid: any): import("rxjs").Observable<Object>;
    saveCriteriaByPageId(data: any): import("rxjs").Observable<Object>;
    getCriteriaByPageId(pageId: any): import("rxjs").Observable<Object>;
    rowVersion(data: any): import("rxjs").Observable<Object>;
    checkDeleteStatus(pageid: any, id: any, primarytable: any): import("rxjs").Observable<Object>;
    checkEditStatus(pageid: any, id: any): import("rxjs").Observable<Object>;
    static ɵfac: i0.ɵɵFactoryDeclaration<DynamicsearchService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<DynamicsearchService>;
}
