import { Location } from '@angular/common';
import { Injector, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormioComponent } from '@formio/angular';
import { AuthService } from '../../@core/services/auth.service';
import { DynamicTabPageService } from '../../@core/services/dynamic-tab-page-service';
import { FormioService } from '../../@core/services/formio.service';
import { LocalService } from '../../@core/services/local.service';
import { PageBuilderViewService } from './@core/page-builder-view.service';
import * as i0 from "@angular/core";
export declare class PageBuilderViewComponent implements OnInit {
    private route;
    private _formIO;
    private pageBuilderViewService;
    private location;
    private localstore;
    formId: any;
    jsonForm: any;
    fromTitle: any;
    id: any;
    submittedData: any;
    isformIO: boolean;
    routingConfig: boolean;
    appointmentList: Promise<boolean> | undefined;
    formIO: FormioComponent;
    dynamicTabPageService: DynamicTabPageService;
    pageid: any;
    editValue: any;
    authService: AuthService;
    loggedUser: any;
    facility: any;
    providerData: any;
    constructor(injector: Injector, route: ActivatedRoute, _formIO: FormioService, pageBuilderViewService: PageBuilderViewService, location: Location, localstore: LocalService);
    ngOnInit(): void;
    conditionCheckPageBuilder(result: any): void;
    modifyVideoContent(): void;
    onSubmit(submission: any): void;
    addAttachment(info: any): void;
    goBack(): void;
    customEvent(event: any): void;
    facilityDetails(id: any, submissionData: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PageBuilderViewComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PageBuilderViewComponent, "app-page-builder-view", never, {}, {}, never, never, false, never>;
}
